import { InvalidTrainableIdentityError } from "./errors.js";

const tokenPrefix = "ts-autocode.trainable";

declare const trainableIdBrand: unique symbol;

/** Stable, serializable identity used across methods, traces, evals, and candidates. */
export type TrainableId = string & { readonly [trainableIdBrand]: true };

/** Runtime identity pairs a durable id with a stable JavaScript symbol. */
export interface TrainableToken {
	readonly id: TrainableId;
	readonly symbol: symbol;
}

/** A function or method that instrumentation has marked trainable: the
 * `@trainable()` decorator, `wrapTrainable`, and `instrumentTrainable` stamp
 * the callable with its identity, so passing the method itself is passing an
 * identity the marking machinery wrote, not one the caller retyped. */
export type TrainableCallable = (...args: never[]) => unknown;

/** Public identity accepted by training APIs: a trainable's symbol (explicit
 * or auto-generated by the decorator), its full token, or the marked method
 * itself, never a raw string. That is an ADR, not a style choice: a plain
 * string is not a sufficient identity to guarantee uniqueness, and accepting
 * one would make every call site an unchecked retyping of it. A revision of
 * this file briefly admitted strings; it was rejected and must not return:
 * `test/tier1.test.ts` pins the rejection at compile time. */
export type TrainableIdentity = symbol | TrainableToken | TrainableCallable;

/** Property key under which marking machinery records a callable's trainable
 * id. A registry symbol on purpose: the rewrite package weaves methods without
 * importing this one, so the stamp must be addressable from any package. */
export const trainableStamp = Symbol.for("ts-autocode.trainable.id");

/** Records `token` as the identity of `fn`. Called by the instrumentation that
 * marks a trainable; never by application code, which is the point: the stamp
 * is written where the identity is declared, so it cannot drift from it. */
export function stampTrainable<F>(fn: F, token: TrainableToken): F {
	if (typeof fn === "function") {
		Object.defineProperty(fn, trainableStamp, { value: token.id, configurable: true });
	}
	return fn;
}

export function defineTrainable(id: string): TrainableToken {
	const normalized = id.trim();
	if (!normalized) {
		throw new InvalidTrainableIdentityError("trainable id must be a non-empty string");
	}
	return Object.freeze({
		id: normalized as TrainableId,
		symbol: Symbol.for(`${tokenPrefix}:${normalized}`),
	});
}

/** In-process index from a user-owned `unique symbol` to the token the
 * marking machinery registered under it. This is what makes
 * `training.train(route)` plain symbol-key indexing: the `@trainable(route)`
 * decorator registers the declaration under the symbol, and every training
 * API that receives the symbol looks it up here. Object identity of the
 * symbol is the uniqueness guarantee: nothing is retyped anywhere. */
const registered = new Map<symbol, TrainableToken>();

/** Binds `identity` (typically an application's own `unique symbol`) to
 * the token the marking machinery derived for a declaration. Called by
 * instrumentation (the `@trainable(symbol)` decorator), never by application
 * code: the registration happens where the declaration is, so the key cannot
 * drift from it. Idempotent for the same id; a symbol cannot be rebound to a
 * different declaration. */
export function registerTrainable(identity: symbol, token: TrainableToken): TrainableToken {
	const existing = registered.get(identity);
	if (existing && existing.id !== token.id) {
		throw new InvalidTrainableIdentityError(
			`symbol ${String(identity)} is already registered to ${existing.id}; one symbol keys one trainable`,
		);
	}
	const bound = Object.freeze({ id: token.id, symbol: identity });
	registered.set(identity, bound);
	return bound;
}

export function toTrainableToken(identity: TrainableIdentity): TrainableToken {
	if (typeof identity === "symbol") {
		const bound = registered.get(identity);
		if (bound) return bound;
		// Registry symbols carry a machinery-derived id in their key; a unique
		// symbol carries nothing until @trainable(symbol) registers it. Falling
		// back to the description here would derive an id from user-typed text
		// (string identity by the back door), and could silently target a
		// different trainable, so an unregistered unique symbol fails loudly.
		if (Symbol.keyFor(identity) !== undefined) return trainableTokenFromSymbol(identity);
		throw new InvalidTrainableIdentityError(
			`symbol ${String(identity)} is not a registered trainable; @trainable(symbol) registers it at first construction of the declaring class`,
		);
	}
	if (typeof identity === "function") {
		const id = (identity as Partial<Record<typeof trainableStamp, unknown>>)[trainableStamp];
		if (typeof id === "string") return defineTrainable(id);
		throw new InvalidTrainableIdentityError(
			`function ${identity.name || "(anonymous)"} is not marked trainable; mark it with @trainable() or load-time instrumentation, or pass the trainable's symbol`,
		);
	}
	if (typeof (identity as TrainableToken | null)?.id === "string") return identity as TrainableToken;
	throw new InvalidTrainableIdentityError("trainable identity must be a symbol or TrainableToken; create one with defineTrainable(id)");
}

/** Strips the library prefix so registered symbols and raw ids share one durable id space. */
export function trainableIdFromKey(key: string): string {
	return key.startsWith(`${tokenPrefix}:`) ? key.slice(tokenPrefix.length + 1) : key;
}

export function trainableTokenFromSymbol(identity: symbol): TrainableToken {
	const key = Symbol.keyFor(identity) ?? identity.description ?? "";
	if (!key.trim()) throw new InvalidTrainableIdentityError("trainable symbol must carry a registry key or description");
	return defineTrainable(trainableIdFromKey(key));
}
