import { InvalidTrainableIdentityError } from "./errors.js";

const tokenPrefix = "ts-autocode.trainable";

declare const trainableIdBrand: unique symbol;

/** Stable, serializable identity used across methods, traces, evals, and candidates. */
export type TrainableId = string & { readonly [trainableIdBrand]: true };

/** Runtime identity pairs a durable id with a stable JavaScript symbol. */
export interface TrainableToken {
	readonly id: TrainableId;
	readonly symbol: symbol;
}

/** A function or method that instrumentation has marked trainable: the
 * `@trainable()` decorator, `wrapTrainable`, and `instrumentTrainable` stamp
 * the callable with its identity, so passing the method itself is passing an
 * identity the marking machinery wrote — not one the caller retyped. */
export type TrainableCallable = (...args: never[]) => unknown;

/** Public identity accepted by training APIs: a trainable's symbol (explicit
 * or auto-generated by the decorator), its full token, or the marked method
 * itself — never a raw string. That is an ADR, not a style choice: a plain
 * string is not a sufficient identity to guarantee uniqueness, and accepting
 * one would make every call site an unchecked retyping of it. A revision of
 * this file briefly admitted strings; it was rejected and must not return —
 * `test/tier1.test.ts` pins the rejection at compile time. */
export type TrainableIdentity = symbol | TrainableToken | TrainableCallable;

/** Property key under which marking machinery records a callable's trainable
 * id. A registry symbol on purpose: the rewrite package weaves methods without
 * importing this one, so the stamp must be addressable from any package. */
export const trainableStamp = Symbol.for("ts-autocode.trainable.id");

/** Records `token` as the identity of `fn`. Called by the instrumentation that
 * marks a trainable; never by application code, which is the point — the stamp
 * is written where the identity is declared, so it cannot drift from it. */
export function stampTrainable<F>(fn: F, token: TrainableToken): F {
	if (typeof fn === "function") {
		Object.defineProperty(fn, trainableStamp, { value: token.id, configurable: true });
	}
	return fn;
}

export function defineTrainable(id: string): TrainableToken {
	const normalized = id.trim();
	if (!normalized) {
		throw new InvalidTrainableIdentityError("trainable id must be a non-empty string");
	}
	return Object.freeze({
		id: normalized as TrainableId,
		symbol: Symbol.for(`${tokenPrefix}:${normalized}`),
	});
}

export function toTrainableToken(identity: TrainableIdentity): TrainableToken {
	if (typeof identity === "symbol") return trainableTokenFromSymbol(identity);
	if (typeof identity === "function") {
		const id = (identity as Partial<Record<typeof trainableStamp, unknown>>)[trainableStamp];
		if (typeof id === "string") return defineTrainable(id);
		throw new InvalidTrainableIdentityError(
			`function ${identity.name || "(anonymous)"} is not marked trainable; mark it with @trainable() or load-time instrumentation, or pass the trainable's symbol`,
		);
	}
	if (typeof (identity as TrainableToken | null)?.id === "string") return identity as TrainableToken;
	throw new InvalidTrainableIdentityError("trainable identity must be a symbol or TrainableToken; create one with defineTrainable(id)");
}

/** Strips the library prefix so registered symbols and raw ids share one durable id space. */
export function trainableIdFromKey(key: string): string {
	return key.startsWith(`${tokenPrefix}:`) ? key.slice(tokenPrefix.length + 1) : key;
}

export function trainableTokenFromSymbol(identity: symbol): TrainableToken {
	const key = Symbol.keyFor(identity) ?? identity.description ?? "";
	if (!key.trim()) throw new InvalidTrainableIdentityError("trainable symbol must carry a registry key or description");
	return defineTrainable(trainableIdFromKey(key));
}
