import { describe, expect, it } from "vitest";

import { generateDeclaredRegistrations, scanDeclaredTrainables } from "../src/index.js";

const ambient = `
import { trainable, intent, returns, description } from "some-runtime";

@trainable
export declare class Program {
	@intent("Produce a simple hello-world program")
	@returns("Hello World! or Hello, <name>! when supplied")
	trainableMethod(
		@description("Optional person to greet")
		name?: string,
	): string;

	other(count: number, extra: Map<string, number>): Promise<string[]>;
}

export class NotTrainable {
	skip(): void {}
}
`;

describe("scanDeclaredTrainables", () => {
	it("scans ambient @trainable classes with granular decorators", () => {
		const classes = scanDeclaredTrainables(ambient);
		expect(classes).toHaveLength(1);
		const program = classes[0];
		expect(program?.className).toBe("Program");
		expect(program?.ambient).toBe(true);
		expect(program?.operations).toEqual([
			{
				methodRef: "Program.trainableMethod",
				method: "trainableMethod",
				intent: "Produce a simple hello-world program",
				inferredIntent: false,
				returns: "Hello World! or Hello, <name>! when supplied",
				contractRef: "decl://Program.trainableMethod",
				parameters: [
					{ name: "name", optional: true, type: "string", description: "Optional person to greet" },
				],
				outputType: "string",
			},
			{
				methodRef: "Program.other",
				method: "other",
				intent: "Inferred: implement Program.other to satisfy its declared signature and descriptions.",
				inferredIntent: true,
				contractRef: "decl://Program.other",
				parameters: [
					{ name: "count", optional: false, type: "number" },
					{ name: "extra", optional: false, type: "Map<string, number>" },
				],
				outputType: "Promise<string[]>",
			},
		]);
	});

	it("scans non-ambient decorated classes and skips constructors", () => {
		const classes = scanDeclaredTrainables(`
			@trainable
			class Impl {
				constructor(private x: number) {}
				run(input: { a: number }): number { return input.a; }
			}
		`);
		expect(classes).toEqual([
			{
				className: "Impl",
				ambient: false,
				operations: [
					{
						methodRef: "Impl.run",
						method: "run",
						intent: "Inferred: implement Impl.run to satisfy its declared signature and descriptions.",
						inferredIntent: true,
						contractRef: "decl://Impl.run",
						parameters: [{ name: "input", optional: false, type: "{ a: number }" }],
						outputType: "number",
					},
				],
			},
		]);
	});

	it("throws on duplicate operation names from ambient overload signatures", () => {
		expect(() =>
			scanDeclaredTrainables(`
				@trainable
				export declare class Over {
					bar(a: string): string;
					bar(a: number): number;
				}
			`),
		).toThrow(/duplicate name.*Over\.bar/);
	});

	it("throws on non-identifier method names", () => {
		expect(() =>
			scanDeclaredTrainables(`
				@trainable
				export declare class Odd {
					["not-an-identifier"](): void;
				}
			`),
		).toThrow(/plain identifier/);
	});

	it("throws on non-string input", () => {
		expect(() => scanDeclaredTrainables(undefined as unknown as string)).toThrow(TypeError);
	});
});

describe("generateDeclaredRegistrations", () => {
	it("emits training.define registrations with a configurable header and runtime module", () => {
		const [program] = scanDeclaredTrainables(ambient);
		const source = generateDeclaredRegistrations(program as NonNullable<typeof program>, {
			runtimeModule: "@hobo/runtime",
			header: [
				"// Generated by hobo stub from an ambient @trainable declaration —",
				"// do not edit by hand (ADR-0037 generated-vs-authored boundary).",
			],
		});
		expect(source).toContain('import { training } from "@hobo/runtime";');
		expect(source).toContain("// Generated by hobo stub from an ambient @trainable declaration —");
		expect(source).toContain("export const trainableMethod = training.define({");
		expect(source).toContain('"ref": "decl://Program.trainableMethod"');
		expect(source).toContain('"description": "Optional person to greet"');
		expect(source).toContain('"output": {\n\t\t"returns": {\n\t\t\t"description": "Hello World! or Hello, <name>! when supplied"\n\t\t}\n\t}');
		expect(source).toContain("export const other = training.define({");
	});
});
